from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional

from ._ddmin import _run, minimize_tape

_PROBE_LIMIT = 40
_FLOAT_ITERS = 50


@dataclass
class Boundary:

    seq: int
    source: str
    tag: str
    original: float
    op: str
    threshold: float
    passing_example: float

    def render(self) -> str:
        rel = "≥" if self.op == ">=" else "≤"
        return (
            f"{self.source} → fails when {rel} {_fmt(self.threshold)} "
            f"(passes at {_fmt(self.passing_example)})"
        )

    def guard(self) -> str:
        inv = "<" if self.op == ">=" else ">"
        return f"assert n {inv} {_fmt(self.threshold)}"


@dataclass
class Generalization:

    reproduced: bool
    total: int
    load_bearing: int
    boundaries: list[Boundary] = field(default_factory=list)
    note: str = ""

    def render(self) -> str:
        if not self.reproduced:
            return "the recording did not reproduce the failure (nothing to generalize)"
        lines = [
            f"minimal reproducer: {self.load_bearing} of {self.total} recorded values matter",
            "generalization (per-value boundary sweep):",
        ]
        if not self.boundaries:
            lines.append("  (no ordered scalar had a findable boundary in range)")
        for b in self.boundaries:
            lines.append(f"  {b.render()}")
            lines.append(f"     ⇒ candidate property: `{b.guard()}` would guard the bug")
        if self.note:
            lines.append(f"  note: {self.note}")
        return "\n".join(lines)

    def as_property(self) -> Optional[str]:
        return self.boundaries[0].guard() if self.boundaries else None

    def as_hypothesis(self, func_name: str = "target") -> str:
        lines = [
            "# Auto-generated by `flight generalize` — a property-test scaffold.",
            "# Fill in how `n` maps to your function's input; the assumes encode",
            "# the empirical safe region the sweep found.",
            "from hypothesis import assume, given, strategies as st",
            "",
            "",
            "@given(n=st.integers())" if self._all_int() else "@given(n=st.floats(allow_nan=False))",
            f"def test_{func_name}_property(n):",
        ]
        for b in self.boundaries:
            keep = f"n < {_fmt(b.threshold)}" if b.op == ">=" else f"n > {_fmt(b.threshold)}"
            lines.append(f"    assume({keep})  # {b.source}: stay out of the failing region")
        lines.append(f"    {func_name}(n)  # should not raise inside the safe region")
        lines.append("")
        return "\n".join(lines)

    def _all_int(self) -> bool:
        return all(b.tag == "i" for b in self.boundaries) if self.boundaries else True


def _fmt(v) -> str:
    if isinstance(v, float):
        return repr(round(v, 12)) if v != int(v) else str(int(v))
    return str(v)


def _encode(tag: str, value) -> str:
    return str(int(value)) if tag == "i" else repr(float(value))


def _reproduces_with(rows, index, value, fn, args, kwargs, interesting) -> bool:
    seq, src, tag, _payload = rows[index]
    trial = list(rows)
    trial[index] = (seq, src, tag, _encode(tag, value))
    return interesting(_run(trial, fn, args, kwargs))


def _find_boundary(rows, index, fn, args, kwargs, interesting) -> Optional[Boundary]:
    seq, src, tag, payload = rows[index]
    try:
        orig = int(payload) if tag == "i" else float(payload)
    except ValueError:
        return None

    def rep(v) -> bool:
        return _reproduces_with(rows, index, v, fn, args, kwargs, interesting)

    if not rep(orig):
        return None

    down = _probe(rep, orig, tag, direction=-1)
    up = _probe(rep, orig, tag, direction=+1)
    if down is None and up is None:
        return None

    if down is not None and (up is None or abs(orig - down) <= abs(up - orig)):
        threshold, passing = _bisect(rep, passing=down, failing=orig, tag=tag)
        return Boundary(seq, src, tag, orig, ">=", threshold, passing)
    threshold, passing = _bisect(rep, passing=up, failing=orig, tag=tag)
    return Boundary(seq, src, tag, orig, "<=", threshold, passing)


def _probe(rep, orig, tag, direction: int):
    step = 1.0
    for _ in range(_PROBE_LIMIT):
        cand = orig + direction * (int(step) if tag == "i" else step)
        if not rep(cand):
            return cand
        step *= 2
    return None


def _bisect(rep, *, passing, failing, tag):
    lo, hi = passing, failing
    if tag == "i":
        while abs(hi - lo) > 1:
            mid = (lo + hi) // 2
            if rep(mid):
                hi = mid
            else:
                lo = mid
        return hi, lo
    for _ in range(_FLOAT_ITERS):
        mid = (lo + hi) / 2.0
        if rep(mid):
            hi = mid
        else:
            lo = mid
    return hi, lo


def generalize_tape(tape, fn, interesting=None, *args, **kwargs) -> Generalization:
    interesting = interesting or (lambda o: o["raised"])
    result = minimize_tape(tape, fn, interesting, *args, **kwargs)
    if not result.reproduced:
        return Generalization(reproduced=False, total=result.total, load_bearing=0)

    rows = tape.rows()
    boundaries: list[Boundary] = []
    for i in result.kept:
        if rows[i][2] not in ("i", "f"):
            continue
        b = _find_boundary(rows, i, fn, args, kwargs, interesting)
        if b is not None:
            boundaries.append(b)
    note = ""
    if len(result.kept) > 1:
        note = "sweep is 1-D per value; interactions between values are not characterized"
    return Generalization(
        reproduced=True,
        total=result.total,
        load_bearing=len(result.kept),
        boundaries=boundaries,
        note=note,
    )


def generalize(flight_path, fn=None, interesting=None, *args, **kwargs) -> Generalization:
    from ._read import read

    fl = read(flight_path)
    if fn is None:
        invocable = load_invocable(fl)
        if invocable is None:
            return Generalization(
                reproduced=False, total=0, load_bearing=0,
                note="could not resolve the crash function from the recording",
            )
        fn, args, kwargs = invocable, (), {}
    return generalize_tape(fl.tape(), fn, interesting, *args, **kwargs)


def load_invocable(fl) -> Optional[Callable[[], object]]:
    from ._repro import _PREAMBLE, _Reconstructor

    if not fl.has_crash:
        return None
    try:
        crash = fl.crash()
    except Exception:
        return None
    if not crash.frames:
        return None
    frame = crash.frames[0]
    source = crash.sources.get(frame.file)
    if not source:
        return None

    mod_ns: dict = {}
    try:
        exec(compile(source, frame.file, "exec"), mod_ns)
    except BaseException:
        pass

    rec = _Reconstructor(crash.objects)
    ref_lines, names = [], []
    for name, oid in frame.locals:
        if name.startswith("__") and name.endswith("__"):
            continue
        ref_lines.append(f"{name}_ref = {rec.build(oid)}")
        names.append(name)
    build = _PREAMBLE + "\n" + "\n".join(rec.lines + ref_lines)
    build_ns: dict = {}
    try:
        exec(compile(build, "<flight-reconstruct>", "exec"), build_ns)
    except BaseException:
        return None
    locals_map = {n: build_ns.get(f"{n}_ref") for n in names}

    fn = mod_ns
    for part in frame.qualname.split("."):
        if part == "<locals>":
            return None
        fn = mod_ns.get(part) if fn is mod_ns else getattr(fn, part, None)
        if fn is None:
            return None
    if not callable(fn):
        return None

    import inspect

    try:
        params = [
            p.name
            for p in inspect.signature(fn).parameters.values()
            if p.kind in (p.POSITIONAL_OR_KEYWORD, p.KEYWORD_ONLY)
        ]
    except (TypeError, ValueError):
        params = list(names)
    call_args = {k: locals_map[k] for k in params if k in locals_map}

    def invoke():
        return fn(**call_args)

    return invoke
